### ISSUE TITLE
Other spatial resampling methods

### ISSUE THREAD

**Issue by juliasilge** [tidymodels/spatialsample#1]
As discussed in tidymodels/rsample#183, there are other spatial resampling methods to add in the future, like those available in:

- https://github.com/rvalavi/blockCV
- https://github.com/mlr-org/mlr3spatiotempcv

**Comment by mschmidty** [comment]
The CAST package has been helpful to me in the past: https://cran.r-project.org/web/packages/CAST/vignettes/CAST-intro.html

**Comment by edzer** [comment]
@HannaMeyer

**Comment by juliasilge** [comment]
Closing this as we are actively working on adding new methods this summer with our intern @mikemahoney218! 🙌 

Feel free to open new issues for discussion on individual resampling methods.
