### ISSUE TITLE
Wrap `clustering_cv()`

### ISSUE THREAD

**Issue by mikemahoney218** [tidymodels/spatialsample#104]
## Feature

Once https://github.com/tidymodels/rsample/pull/352 is merged, it would be nice for `spatial_clustering_cv()` to become a thin wrapper on top of `clustering_cv()`, the same way that our vfold functions wrap `vfold_cv()` with optional buffering.

**Comment by juliasilge** [comment]
We discussed in our meeting today a plan for:

1. CRAN release of rsample _without_ the clustering CV change
2. Merge in clustering CV to rsample
3. Next CRAN release for rsample a while after that
4. Make this thin wrapper here in spatialsample

I think this is a great change but I'd prefer to have clustering CV in the development version for a bit before release.
