### ISSUE TITLE
Add ability to do repeated cross-validation

### ISSUE THREAD

**Issue by andtheWings** [tidymodels/spatialsample#115]
As with `rsample::vfold_cv()` add the `repeats =` argument so that repeated cross-validation can be performed.

**Comment by mikemahoney218** [comment]
Thanks! This makes sense as an improvement for the package.

For what it's worth, the CRAN version of `spatial_buffer_vfold_cv()` should already have the `repeats` argument, though I just noticed there's a bug which means the `id` column containing the repeat ID is accidentally dropped:

``` r
library(spatialsample)

spatial_buffer_vfold_cv(
  boston_canopy, 
  v = 2, 
  buffer = 1, 
  radius = NULL, 
  repeats = 2
)
#> #  2-fold spatial cross-validation 
#> # A tibble: 4 × 2
#>   splits           id   
#>   <list>           <chr>
#> 1 <split [20/341]> Fold1
#> 2 <split [19/341]> Fold2
#> 3 <split [30/341]> Fold3
#> 4 <split [31/341]> Fold4
```

<sup>Created on 2022-11-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

That said, it makes sense to me that the other functions could also get a `repeat` argument. Each function _can_ be deterministic, though, which we'd want to check for:

1. `spatial_block_cv()` is deterministic unless `method = "random"`, so we'd want to throw errors if repeats would be identical.
2. `spatial_leave_location_out_cv()` is deterministic by default (that is, unless `v` is set), and we'd probably want to error here as well.
3. `spatial_buffer_vfold_cv()` _can_ be deterministic (if `v` is equal to `nrow(data)`, or `NULL`, or `Inf`) and we'd probably want to error _there_ as well (although, that's starting to get into the realm of "if you found this edge case, you were doing something weird on purpose")
4. `spatial_clustering_cv()` _can_ be deterministic depending on `cluster_function`, but there's no way we'd check for that. But, like with `spatial_buffer_vfold_cv()`, that feels fine to me.

**Comment by andtheWings** [comment]
Ahh, didn't catch that, I was just looking at `spatial_clustering_cv()`, but I agree it would be nice if all of them had the option. Thank you!

**Comment by andtheWings** [comment]
Sorry, didn't mean to close the issue.

**Comment by andtheWings** [comment]
Closing since separate issues were made for each function
