### ISSUE TITLE
Spatial data and tidymodels.

### ISSUE THREAD

**Issue by nipnipj** [tidymodels/spatialsample#14]
When using spatial data with coordinates as features in a regression model within tidymodels frameworks, the only part that I need to modify in my script/workflow is the cv folds function from `vfold_cv` to `spatial_clustering_cv`, right? I mean the fomula --- y = lng + lat +x x1 + x2 ---  remains the same across the training, validation, and prediction. There is no need to modify other function within the workflow or when tuning it.

**Comment by juliasilge** [comment]
That's right; the rest of your modeling analysis won't usually change. Folks who do predictive modeling with spatial data use a lot of the same algorithms and approaches.

I think it would be unusual to use your spatial coordinates (`lng`, `lat`) as predictors, though. If your other predictors exhibit spatial autocorrelation, I don't think that including the spatial coordinates would typically be the best choice.

**Comment by juliasilge** [comment]
Let us know if you have other questions! 🙌
