### ISSUE TITLE
Re-export rsample helper functions

### ISSUE THREAD

**Issue by mikemahoney218** [tidymodels/spatialsample#143]
## Feature

It would be nice if spatialsample re-exported functions like get_rsplit(), and possibly analysis() and assessment(), so that spatialsample could be used on its own without also needing to load rsample (either via library() or `::`). 

If those functions were re-exported, it might also be useful to re-export a handful of other one-off utilities. I'm thinking rsample::reshuffle_rset() and _maybe_ rsample::reverse_splits(), though I don't entirely remember the original use-case for that function.

**Comment by hfrick** [comment]
Or put rsample in Depends? 🤔

**Comment by EmilHvitfeldt** [comment]
I would suggest putting rsample in depends, the same way the recipes extension packages do with recipes

**Comment by mikemahoney218** [comment]
I personally don't love putting rsample in Depends; while under the hood spatialsample is extending rsample, from the user's perspective you don't need to know that rsample exists in order to use spatialsample. I think that makes it different from recipes extension packages -- in those, it's reasonable to assume that you'll use functions from recipes in the course of normal usage (at least `recipe()`), while if you use spatialsample with the rest of tidymodels you'd never need to touch an rsample function. I also think it's non-desirable for all the non-spatial CV functions to get dumped into the environment, since it might suggest those are viable alternatives to the spatial CV functions.
