### ISSUE TITLE
Add `spatialsample` (or `spatial_rset`) class to objects

### ISSUE THREAD

**Issue by mikemahoney218** [tidymodels/spatialsample#26]
## Feature

Related to #24 , right now there's no way to tell that an `rset` object came from this package without checking the very specific class associated (eg `spatial_clustering_cv`). Our planned `autoplot` method will need an obvious way to map data to an XY plane (usually via their geometry column, though the non-sf `spatial_clustering_cv` method introduces some complexity here), so having a way to indicate "this `rset` came from `spatialsample`" will be useful.

**Comment by juliasilge** [comment]
This just needs a bit of clean-up, right @mikemahoney218? We need to clarify the `@return` for methods to document when this gets added.

**Comment by juliasilge** [comment]
Closed in #37
