### ISSUE TITLE
spatialsample::spatial_clustering_cv() for Tidymodels -- coords removed for prediction or no?

### ISSUE THREAD

**Issue by PathosEthosLogos** [tidymodels/spatialsample#32]
I was just wondering if setting `spatial_clustering_cv(v, coords = c(x, y)` would keep `x` and `y` as predictors or would be removed (like `id` or `strata` would be).

How can I check this?

**Comment by hfrick** [comment]
I'm not entirely sure what you mean here. rsample and spatialsample do not have predictors, they only resample the data. No columns get removed. Does this answer help you?

**Comment by PathosEthosLogos** [comment]
>I'm not entirely sure what you mean here. rsample and spatialsample do not have predictors, they only resample the data. No columns get removed. Does this answer help you?

Thanks for the reply @hfrick. Sorry it was unclear.
The scenario is:
* set up a spatial cross validation with the two columns for the argument `coords`
* set up recipe (`y ~ .`)
* tune hyperparameters for elastic net (or any other algorithm)

One example I would like to cite is `update_role(..., new_role = 'ID')`. Once role is applied to a particular column, they are removed as predictors. I was wondering if `coords` argument does something similar.

**Comment by hfrick** [comment]
Ah, I see, thanks. Resampling only splits the data. The columns you declare as `coords` will still be part of the data and their role will be what you declare in the recipe.

**Comment by mikemahoney218** [comment]
Let us know if you have further clarifications or questions :smile:
