### ISSUE TITLE
Update indentation

### ISSUE THREAD

**Issue by mikemahoney218** [tidymodels/spatialsample#34]
A good bit of the test suite (and some core code) should be re-styled following https://style.tidyverse.org/syntax.html, particularly with regards to long lines. I think it'd make sense to do this when there's a few fewer PRs to conflict with.

**Comment by mikemahoney218** [comment]
:crossed_fingers: 

I know there's a lot of examples of the sort of thing I just fixed in 2eb6c0ef4fba90ef4d86bc31d10e31b081d8d639, for instance:

https://github.com/tidymodels/spatialsample/blob/9e4d7970881b4df3c0a6726af61553fa3ecdd4b9/tests/testthat/test-spatial_clustering_cv.R#L10-L19

So I don't imagine there's a _ton_ of issues, but this particular lint is in enough places that I think it would cause conflicts with #22 and #31 .

**Comment by juliasilge** [comment]
Closed in #37
