### ISSUE TITLE
Run tests in parallel?

### ISSUE THREAD

**Issue by mikemahoney218** [tidymodels/spatialsample#40]
As we start adding more tests for the same functions, it may be helpful to start [running tests in parallel](https://testthat.r-lib.org/articles/parallel.html) to speed up CI somewhat. Are there any drawbacks to this?

**Comment by juliasilge** [comment]
We'd need to make sure the tests don't rely on side effects of each other (this is pretty easy to have happen). 

FWIW the GH actions workers have, I think, just 2 subprocesses, so I'm not sure this is going to have a big benefit? Might be worth looking into, though.

**Comment by mikemahoney218** [comment]
Closed in #41
