### ISSUE TITLE
Default alpha in autoplot?

### ISSUE THREAD

**Issue by mikemahoney218** [tidymodels/spatialsample#55]
Julia has mentioned (https://github.com/tidymodels/spatialsample/pull/49#pullrequestreview-1003026650 , https://github.com/tidymodels/spatialsample/pull/54#pullrequestreview-1002930553 ) wanting a different default alpha for the autoplot method. Here's what different values could look like:
``` r
library(spatialsample)

set.seed(123)
boston_vfold_buffer <- spatial_buffer_vfold_cv(
  boston_canopy,
  v = 682,
  radius = 1,
  buffer = 5000
)

lapply(
  seq(0.1, 1, 0.1),
  \ (x) autoplot(boston_vfold_buffer$splits[[4]], alpha = x)
)
#> [[1]]
```

![](https://i.imgur.com/hkbLKx4.png)

    #> 
    #> [[2]]

![](https://i.imgur.com/c8QBw5O.png)

    #> 
    #> [[3]]

![](https://i.imgur.com/CU15GUv.png)

    #> 
    #> [[4]]

![](https://i.imgur.com/CoDYJzL.png)

    #> 
    #> [[5]]

![](https://i.imgur.com/0f3ngzj.png)

    #> 
    #> [[6]]

![](https://i.imgur.com/0IS5qlS.png)

    #> 
    #> [[7]]

![](https://i.imgur.com/PmEwUFB.png)

    #> 
    #> [[8]]

![](https://i.imgur.com/PyBOc4u.png)

    #> 
    #> [[9]]

![](https://i.imgur.com/0BAxjwi.png)

    #> 
    #> [[10]]

![](https://i.imgur.com/VKcAfzM.png)

<sup>Created on 2022-06-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mikemahoney218** [comment]
Personally, I don't mind the current default, particularly because we can pass values via `...`. But I'm open to changing if others think the default is a bit much.

**Comment by juliasilge** [comment]
I do think this is an improvement, and I prefer something in the 0.5 - 0.7 range.
