### ISSUE TITLE
We could signal silly grids better

### ISSUE THREAD

**Issue by mikemahoney218** [tidymodels/spatialsample#67]
## The problem

It's a little too easy right now to create silly grids. For instance, using our Boston data set:

``` r
library(spatialsample)
x <- spatial_block_cv(boston_canopy, n = c(200, 200), v = Inf)
#> Warning in spatial_block_cv(boston_canopy, n = c(200, 200), v = Inf): Fewer than Inf blocks available for sampling
#> ℹ Setting `v` to 682
autoplot(x) + ggplot2::theme(legend.position = "none")
#> Coordinate system already present. Adding new coordinate system, which will replace the existing one.
```

![](https://i.imgur.com/zi8LcOb.png)

This grid is obviously mis-matched to the data, since 98% of blocks are getting thrown out. However, it's not wild to think that sometimes you _expect_ the majority of blocks to get thrown away; for instance when blocking with island data:

``` r
boston_canopy[grep("^(A-|B|C|D|E|F|G|AQ|AP|AO|AN|AN|AL)", boston_canopy$grid_id), ] |> 
  spatial_block_cv() |> 
  autoplot()
#> Coordinate system already present. Adding new coordinate system, which will replace the existing one.
```

![](https://i.imgur.com/0MJTRpT.png)

<sup>Created on 2022-06-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

It'd be nice to have some messaging around this situation. Two possibilities:

* Have an `rlang::inform()` call send a message whenever more than a certain threshold of blocks are thrown away
* Add a new argument (`warning_threshold`?) which defaults to a high value, and warn if less than `warning_threshold`% of blocks are used

**Comment by juliasilge** [comment]
There is already [some infrastructure for silencing `rlang::inform()` messages](https://rlang.r-lib.org/reference/abort.html#muffling-and-silencing-conditions), so if we use the first option we could point folks there to silence them, if they prefer. You can see how I point this out for vetiver here:
<https://rstudio.github.io/vetiver-r/articles/model-card.html>

**Comment by mikemahoney218** [comment]
We're going to go ahead and use `rlang::inform()` (and possibly sub-class the message so it can be silenced via options)
